version: '3.1'

volumes:
  tasks-data:
    driver: local

services:
  db:
    image: postgres:11.5
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tasks_db
    volumes:
      - tasks-data:/var/lib/postgresql/data:rw
